In [1]:
import pandas as pd
from pathlib import Path
import re
from IPython.display import display
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
BASE_DIR = Path.cwd().parent
CHAMPIONS_LEAGUE_DATA_DIR = BASE_DIR / "data" / "raw" / "champions_league"
EUROPA_LEAGUE_DATA_DIR = BASE_DIR / "data" / "raw" / "europa_league"
CONFERENCE_LEAGUE_DATA_DIR = BASE_DIR / "data" / "raw" / "conference_league"

DATA_PROCESSED_DIR = BASE_DIR / "data" / "processed" 

CONFERENCE_LEAGUE_DATA_PROCESSED_DIR = BASE_DIR / "data" / "processed" / "conference_league"
EUROPA_LEAGUE_DATA_PROCESSED_DIR = BASE_DIR / "data" / "processed" / "europa_league"
CHAMPIONS_LEAGUE_DATA_PROCESSED_DIR = BASE_DIR / "data" / "processed" / "champions_league"

In [4]:
df_all_european_competition_matches = pd.read_csv(f"{DATA_PROCESSED_DIR}/all_european_competition_matches.csv")
df_champions_league_matches = pd.read_csv(f"{DATA_PROCESSED_DIR}/champions_league_matches.csv")
df_europa_league_matches = pd.read_csv(f"{DATA_PROCESSED_DIR}/europa_league_matches.csv")
df_conference_league_matches = pd.read_csv(f"{DATA_PROCESSED_DIR}/conference_league_matches.csv")

In [5]:
# checking if union of all competitions has been performed correctly in "all_european_competition_matches.csv"

In [6]:
df_all_european_competition_matches

,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
0,Conference League,2021/22,2021,Group stage,1.0,Wed,2021-09-15,17:30,ru,Spartak Moscow,0.0,0–1,pl,Legia Warsaw,1.0,6832.0,Stadion Akademii imeni Cherenkova № 4,Nikola Dabanović,NaN,main stage,NaN,NaN,NaN,NaN,NaN
1,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,es,Real Betis,4.0,4–3,sct,Celtic,3.0,30893.0,Estadio Benito Villamarín,Fran Jović,NaN,main stage,NaN,NaN,NaN,NaN,NaN
2,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,at,Rapid Wien,0.0,0–1,be,Genk,1.0,18400.0,Gerhard-Hanappi-Stadion,Kristo Tohver,NaN,main stage,NaN,NaN,NaN,NaN,NaN
3,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,rs,Red Star,2.0,2–1,pt,Braga,1.0,24671.0,Stadion Rajko Mitić,John Beaton,NaN,main stage,NaN,NaN,NaN,NaN,NaN
4,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,de,Leverkusen,2.0,2–1,hu,Ferencváros,1.0,11013.0,BayArena,Andris Treimanis,NaN,main stage,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4017,Champions League,2026/27,2026,Play-off round,NaN,Tue,2026-08-25,21:00,no,Bodø/Glimt,3.0,3–0,nl,NEC Nijmegen,0.0,8009.0,Aspmyra Stadion,Michael Oliver,Leg 2 of 2; Bodø/Glimt won,qualification,False,False,NaN,NaN,NaN
4018,Champions League,2026/27,2026,Play-off round,NaN,Wed,2026-08-26,21:00,fr,Lyon,1.0,1–2,tr,Fenerbahçe,2.0,55443.0,Groupama Stadium,Maurizio Mariani,Leg 2 of 2; Fenerbahçe won,qualification,False,False,NaN,NaN,NaN
4019,Champions League,2026/27,2026,Play-off round,NaN,Wed,2026-08-26,21:00,no,Viking,3.0,3–1,hr,Dinamo Zagreb,1.0,15152.0,Lyse Arena,Jose Maria Sánchez,Leg 2 of 2; Viking won,qualification,False,False,NaN,NaN,NaN
4020,Champions League,2026/27,2026,Play-off round,NaN,Wed,2026-08-26,21:00,si,NK Celje,1.0,1–2,sk,Slovan Bratislava,2.0,11500.0,Stadion Z'dežele,Alejandro Hernández,Leg 2 of 2; Slovan Bratislava won; Required Ex...,qualification,True,False,NaN,NaN,NaN
4021,Champions League,2026/27,2026,Play-off round,NaN,Wed,2026-08-26,22:00,gr,AEK Athens,4.0,4–0,bg,Levski Sofia,0.0,30500.0,Agia Sophia Stadium,Clément Turpin,Leg 2 of 2; AEK Athens won,qualification,False,False,NaN,NaN,NaN

In [ ]:
# checking if dataformats of each file is correctly recognized by Pandas before imnporting tables to Postgres Databaes

In [19]:
df_all_european_competition_matches.head(5)

,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
0,Conference League,2021/22,2021,Group stage,1.0,Wed,2021-09-15,17:30,ru,Spartak Moscow,0.0,0–1,pl,Legia Warsaw,1.0,6832.0,Stadion Akademii imeni Cherenkova № 4,Nikola Dabanović,NaN,main stage,False,False,NaN,NaN,NaN
1,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,es,Real Betis,4.0,4–3,sct,Celtic,3.0,30893.0,Estadio Benito Villamarín,Fran Jović,NaN,main stage,False,False,NaN,NaN,NaN
2,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,at,Rapid Wien,0.0,0–1,be,Genk,1.0,18400.0,Gerhard-Hanappi-Stadion,Kristo Tohver,NaN,main stage,False,False,NaN,NaN,NaN
3,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,rs,Red Star,2.0,2–1,pt,Braga,1.0,24671.0,Stadion Rajko Mitić,John Beaton,NaN,main stage,False,False,NaN,NaN,NaN
4,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,de,Leverkusen,2.0,2–1,hu,Ferencváros,1.0,11013.0,BayArena,Andris Treimanis,NaN,main stage,False,False,NaN,NaN,NaN

In [23]:
df_all_european_competition_matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 3590 entries, 0 to 3589
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Competition             3590 non-null   str
 1   Season                  3590 non-null   str
 2   Season start year       3590 non-null   int64
 3   Round                   3590 non-null   str
 4   Matchweek               1728 non-null   float64
 5   Day                     3590 non-null   str
 6   Date                    3590 non-null   str
 7   Time                    3588 non-null   str
 8   Host country            3590 non-null   str
 9   Host                    3590 non-null   str
 10  Host goals              3524 non-null   float64
 11  Score                   3524 non-null   str
 12  Guest country           3590 non-null   str
 13  Guest                   3590 non-null   str
 14  Guest goals             3524 non-null   float64
 15  Attendance              3486 non-null   float64
 16  Venue                   3588 non-null   str
 17  Referee                 3524 non-null   str
 18  Notes                   1843 non-null   str
 19  Competition phase       3590 non-null   str
 20  Extra time              3590 non-null   bool
 21  Penalty kicks           3590 non-null   bool
 22  Penalty kicks result    82 non-null     str
 23  Host penalties scored   82 non-null     float64
 24  Guest penalties scored  82 non-null     float64
dtypes: bool(2), float64(6), int64(1), str(16)
memory usage: 652.2 KB

In [20]:
df_champions_league_matches.head(5)

,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
0,Champions League,2021/22,2021,Group stage,1.0,Tue,2021-09-14,18:45,es,Sevilla,1.0,1–1,at,RB Salzburg,1.0,18373.0,Estadio Ramón Sánchez Pizjuán,Aliaksei Kulbakou,NaN,main stage,False,False,NaN,NaN,NaN
1,Champions League,2021/22,2021,Group stage,1.0,Tue,2021-09-14,18:45,ch,Young Boys,2.0,2–1,eng,Manchester Utd,1.0,31120.0,Wankdorfstadion,François Letexier,NaN,main stage,False,False,NaN,NaN,NaN
2,Champions League,2021/22,2021,Group stage,1.0,Tue,2021-09-14,20:00,eng,Chelsea,1.0,1–0,ru,Zenit,0.0,39252.0,Stamford Bridge,Bartosz Frankowski,NaN,main stage,False,False,NaN,NaN,NaN
3,Champions League,2021/22,2021,Group stage,1.0,Tue,2021-09-14,21:00,es,Villarreal,2.0,2–2,it,Atalanta,2.0,12916.0,Estadio de la Cerámica,Clément Turpin,NaN,main stage,False,False,NaN,NaN,NaN
4,Champions League,2021/22,2021,Group stage,1.0,Tue,2021-09-14,21:00,es,Barcelona,0.0,0–3,de,Bayern Munich,3.0,39737.0,Camp Nou,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN

In [21]:
df_europa_league_matches.head(5)

,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
0,Europa League,2021/22,2021,Group stage,1.0,Wed,2021-09-15,17:30,ru,Spartak Moscow,0.0,0–1,pl,Legia Warsaw,1.0,6832.0,Stadion Akademii imeni Cherenkova № 4,Nikola Dabanović,NaN,main stage,False,False,NaN,NaN,NaN
1,Europa League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,es,Real Betis,4.0,4–3,sct,Celtic,3.0,30893.0,Estadio Benito Villamarín,Fran Jović,NaN,main stage,False,False,NaN,NaN,NaN
2,Europa League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,at,Rapid Wien,0.0,0–1,be,Genk,1.0,18400.0,Gerhard-Hanappi-Stadion,Kristo Tohver,NaN,main stage,False,False,NaN,NaN,NaN
3,Europa League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,rs,Red Star,2.0,2–1,pt,Braga,1.0,24671.0,Stadion Rajko Mitić,John Beaton,NaN,main stage,False,False,NaN,NaN,NaN
4,Europa League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,de,Leverkusen,2.0,2–1,hu,Ferencváros,1.0,11013.0,BayArena,Andris Treimanis,NaN,main stage,False,False,NaN,NaN,NaN

In [22]:
df_conference_league_matches.head(5)

,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
0,Conference League,2021/22,2021,Group stage,1.0,Wed,2021-09-15,17:30,ru,Spartak Moscow,0.0,0–1,pl,Legia Warsaw,1.0,6832.0,Stadion Akademii imeni Cherenkova № 4,Nikola Dabanović,NaN,main stage,False,False,NaN,NaN,NaN
1,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,es,Real Betis,4.0,4–3,sct,Celtic,3.0,30893.0,Estadio Benito Villamarín,Fran Jović,NaN,main stage,False,False,NaN,NaN,NaN
2,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,at,Rapid Wien,0.0,0–1,be,Genk,1.0,18400.0,Gerhard-Hanappi-Stadion,Kristo Tohver,NaN,main stage,False,False,NaN,NaN,NaN
3,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,rs,Red Star,2.0,2–1,pt,Braga,1.0,24671.0,Stadion Rajko Mitić,John Beaton,NaN,main stage,False,False,NaN,NaN,NaN
4,Conference League,2021/22,2021,Group stage,1.0,Thu,2021-09-16,18:45,de,Leverkusen,2.0,2–1,hu,Ferencváros,1.0,11013.0,BayArena,Andris Treimanis,NaN,main stage,False,False,NaN,NaN,NaN

In [15]:
pd.set_option('display.max_rows', None)
df_uefa_competitions[(df_uefa_competitions['Season start year'] == 2025) & (df_uefa_competitions['Competition'] == 'Champions League')]

,Unnamed: 0,Competition,Season,Season start year,Round,Matchweek,Day,Date,Time,Host country,Host,Host goals,Score,Guest country,Guest,Guest goals,Attendance,Venue,Referee,Notes,Competition phase,Extra time,Penalty kicks,Penalty kicks result,Host penalties scored,Guest penalties scored
3219,969,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,18:45,nl,PSV,1.0,1–3,be,Union SG,3.0,35000.0,Philips Stadion,Anthony Taylor,NaN,main stage,False,False,NaN,NaN,NaN
3220,970,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,18:45,es,Athletic Club,0.0,0–2,eng,Arsenal,2.0,51059.0,San Mamés,Donatas Rumšas,NaN,main stage,False,False,NaN,NaN,NaN
3221,971,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,20:00,pt,Benfica,2.0,2–3,az,Qarabağ,3.0,53257.0,Estádio do Sport Lisboa e Benfica,Erik Lambrechts,NaN,main stage,False,False,NaN,NaN,NaN
3222,972,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,20:00,eng,Tottenham,1.0,1–0,es,Villarreal,0.0,54755.0,Tottenham Hotspur Stadium,Rade Obrenović,NaN,main stage,False,False,NaN,NaN,NaN
3223,973,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,21:00,es,Real Madrid,2.0,2–1,fr,Marseille,1.0,74610.0,Estadio Santiago Bernabéu,Irfan Peljto,NaN,main stage,False,False,NaN,NaN,NaN
3224,974,Champions League,2025/26,2025,League phase,1.0,Tue,2025-09-16,21:00,it,Juventus,4.0,4–4,de,Dortmund,4.0,41497.0,Allianz Stadium,François Letexier,NaN,main stage,False,False,NaN,NaN,NaN
3225,975,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,18:45,cz,Slavia Prague,2.0,2–2,no,Bodø/Glimt,2.0,18922.0,Fortuna Arena,Marian Barbu,NaN,main stage,False,False,NaN,NaN,NaN
3226,976,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,19:45,gr,Olympiacos,0.0,0–0,cy,Pafos FC,0.0,32050.0,Stadio Georgios Karaiskáki,István Kovács,NaN,main stage,False,False,NaN,NaN,NaN
3227,977,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,20:00,eng,Liverpool,3.0,3–2,es,Atlético Madrid,2.0,59507.0,Anfield,Maurizio Mariani,NaN,main stage,False,False,NaN,NaN,NaN
3228,978,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,21:00,fr,PSG,4.0,4–0,it,Atalanta,0.0,47151.0,Parc des Princes,Sandro Schärer,NaN,main stage,False,False,NaN,NaN,NaN
3229,979,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,21:00,de,Bayern Munich,3.0,3–1,eng,Chelsea,1.0,75000.0,Allianz Arena,Jose Maria Sánchez,NaN,main stage,False,False,NaN,NaN,NaN
3230,980,Champions League,2025/26,2025,League phase,1.0,Wed,2025-09-17,21:00,nl,Ajax,0.0,0–2,it,Inter,2.0,52288.0,Johan Cruijff Arena,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN
3231,981,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,18:45,dk,FC Copenhagen,2.0,2–2,de,Leverkusen,2.0,34504.0,Parken,Əliyar Ağayev,NaN,main stage,False,False,NaN,NaN,NaN
3232,982,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,18:45,be,Club Brugge,4.0,4–1,fr,Monaco,1.0,25007.0,Jan Breydelstadion,Simone Sozza,NaN,main stage,False,False,NaN,NaN,NaN
3233,983,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,20:00,eng,Newcastle,1.0,1–2,es,Barcelona,2.0,52084.0,St James' Park,Glenn Nyberg,NaN,main stage,False,False,NaN,NaN,NaN
3234,984,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,20:00,pt,Sporting CP,4.0,4–1,kz,FC Kairat,1.0,38696.0,Estádio José Alvalade,Damian Sylwestrzak,NaN,main stage,False,False,NaN,NaN,NaN
3235,985,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,20:00,eng,Manchester City,2.0,2–0,it,Napoli,0.0,49531.0,Etihad Stadium,Felix Zwayer,NaN,main stage,False,False,NaN,NaN,NaN
3236,986,Champions League,2025/26,2025,League phase,1.0,Thu,2025-09-18,21:00,de,Frankfurt,5.0,5–1,tr,Galatasaray,1.0,58700.0,Deutsche Bank Park,Marco Guida,NaN,main stage,False,False,NaN,NaN,NaN
3237,988,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,18:45,it,Atalanta,2.0,2–1,be,Club Brugge,1.0,21950.0,New Balance Arena,Espen Eskås,NaN,main stage,False,False,NaN,NaN,NaN
3238,989,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,20:00,eng,Chelsea,1.0,1–0,pt,Benfica,0.0,38636.0,Stamford Bridge,Daniel Siebert,NaN,main stage,False,False,NaN,NaN,NaN
3239,990,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,21:00,it,Inter,3.0,3–0,cz,Slavia Prague,0.0,62317.0,Stadio Giuseppe Meazza,Chris Kavanagh,NaN,main stage,False,False,NaN,NaN,NaN
3240,991,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,21:00,no,Bodø/Glimt,2.0,2–2,eng,Tottenham,2.0,7988.0,Aspmyra Stadion,Ivan Kružliak,NaN,main stage,False,False,NaN,NaN,NaN
3241,992,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,21:00,fr,Marseille,4.0,4–0,nl,Ajax,0.0,65771.0,Orange Vélodrome,Anthony Taylor,NaN,main stage,False,False,NaN,NaN,NaN
3242,993,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,21:00,es,Atlético Madrid,5.0,5–1,de,Frankfurt,1.0,59401.0,Riyadh Air Metropolitano,Slavko Vinčič,NaN,main stage,False,False,NaN,NaN,NaN
3243,994,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,21:45,kz,FC Kairat,0.0,0–5,es,Real Madrid,5.0,22788.0,Ortalıq Stadion,Marco Guida,NaN,main stage,False,False,NaN,NaN,NaN
3244,995,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,22:00,cy,Pafos FC,1.0,1–5,de,Bayern Munich,5.0,9187.0,Alphamega Stadium,Manfredas Lukjančukas,NaN,main stage,False,False,NaN,NaN,NaN
3245,996,Champions League,2025/26,2025,League phase,2.0,Tue,2025-09-30,22:00,tr,Galatasaray,1.0,1–0,eng,Liverpool,0.0,50651.0,RAMS Park,Clément Turpin,NaN,main stage,False,False,NaN,NaN,NaN
3246,997,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,18:45,be,Union SG,0.0,0–4,eng,Newcastle,4.0,16038.0,Lotto Park,Urs Schnyder,NaN,main stage,False,False,NaN,NaN,NaN
3247,998,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,20:00,eng,Arsenal,2.0,2–0,gr,Olympiacos,0.0,56820.0,Emirates Stadium,François Letexier,NaN,main stage,False,False,NaN,NaN,NaN
3248,999,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,20:45,az,Qarabağ,2.0,2–0,dk,FC Copenhagen,0.0,30250.0,Tofiq Bəhramov adına Respublika stadionu,Serdar Gözübüyük,NaN,main stage,False,False,NaN,NaN,NaN
3249,1000,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,es,Barcelona,1.0,1–2,fr,PSG,2.0,50207.0,Estadi Olímpic Lluís Companys,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN
3250,1001,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,it,Napoli,2.0,2–1,pt,Sporting CP,1.0,47364.0,Stadio Diego Armando Maradona,Danny Makkelie,NaN,main stage,False,False,NaN,NaN,NaN
3251,1002,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,de,Dortmund,4.0,4–1,es,Athletic Club,1.0,81365.0,Signal Iduna Park,Szymon Marciniak,NaN,main stage,False,False,NaN,NaN,NaN
3252,1003,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,es,Villarreal,2.0,2–2,it,Juventus,2.0,20087.0,Estadio de la Cerámica,István Kovács,NaN,main stage,False,False,NaN,NaN,NaN
3253,1004,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,fr,Monaco,2.0,2–2,eng,Manchester City,2.0,11275.0,Stade Louis II,Jesús Gil,NaN,main stage,False,False,NaN,NaN,NaN
3254,1005,Champions League,2025/26,2025,League phase,2.0,Wed,2025-10-01,21:00,de,Leverkusen,1.0,1–1,nl,PSV,1.0,30210.0,BayArena,Glenn Nyberg,NaN,main stage,False,False,NaN,NaN,NaN
3255,1007,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,18:45,es,Barcelona,6.0,6–1,gr,Olympiacos,1.0,46264.0,Estadi Olímpic Lluís Companys,Urs Schnyder,NaN,main stage,False,False,NaN,NaN,NaN
3256,1008,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,20:00,eng,Newcastle,3.0,3–0,pt,Benfica,0.0,52073.0,St James' Park,Szymon Marciniak,NaN,main stage,False,False,NaN,NaN,NaN
3257,1009,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,20:00,eng,Arsenal,4.0,4–0,es,Atlético Madrid,0.0,59200.0,Emirates Stadium,Davide Massa,NaN,main stage,False,False,NaN,NaN,NaN
3258,1010,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:00,dk,FC Copenhagen,2.0,2–4,de,Dortmund,4.0,35058.0,Parken,Danny Makkelie,NaN,main stage,False,False,NaN,NaN,NaN
3259,1011,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:00,be,Union SG,0.0,0–4,it,Inter,4.0,16632.0,Lotto Park,Glenn Nyberg,NaN,main stage,False,False,NaN,NaN,NaN
3260,1012,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:00,es,Villarreal,0.0,0–2,eng,Manchester City,2.0,20539.0,Estadio de la Cerámica,Serdar Gözübüyük,NaN,main stage,False,False,NaN,NaN,NaN
3261,1013,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:00,de,Leverkusen,2.0,2–7,fr,PSG,7.0,30210.0,BayArena,Jesús Gil,NaN,main stage,False,False,NaN,NaN,NaN
3262,1014,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:00,nl,PSV,6.0,6–2,it,Napoli,2.0,34700.0,Philips Stadion,Daniel Siebert,NaN,main stage,False,False,NaN,NaN,NaN
3263,1015,Champions League,2025/26,2025,League phase,3.0,Tue,2025-10-21,21:45,kz,FC Kairat,0.0,0–0,cy,Pafos FC,0.0,16478.0,Ortalıq Stadion,Chris Kavanagh,NaN,main stage,False,False,NaN,NaN,NaN
3264,1016,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,18:45,es,Athletic Club,3.0,3–1,az,Qarabağ,1.0,50741.0,San Mamés,Igor Pajač,NaN,main stage,False,False,NaN,NaN,NaN
3265,1017,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,19:45,tr,Galatasaray,3.0,3–1,no,Bodø/Glimt,1.0,45275.0,RAMS Park,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN
3266,1018,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,20:00,eng,Chelsea,5.0,5–1,nl,Ajax,1.0,38947.0,Stamford Bridge,Felix Zwayer,NaN,main stage,False,False,NaN,NaN,NaN
3267,1019,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,20:00,pt,Sporting CP,2.0,2–1,fr,Marseille,1.0,46766.0,Estádio José Alvalade,Rade Obrenović,NaN,main stage,False,False,NaN,NaN,NaN
3268,1020,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,21:00,de,Bayern Munich,4.0,4–0,be,Club Brugge,0.0,75000.0,Allianz Arena,Donatas Rumšas,NaN,main stage,False,False,NaN,NaN,NaN
3269,1021,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,21:00,de,Frankfurt,1.0,1–5,eng,Liverpool,5.0,58700.0,Deutsche Bank Park,François Letexier,NaN,main stage,False,False,NaN,NaN,NaN
3270,1022,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,21:00,it,Atalanta,0.0,0–0,cz,Slavia Prague,0.0,22152.0,New Balance Arena,Ricardo de Burgos,NaN,main stage,False,False,NaN,NaN,NaN
3271,1023,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,21:00,fr,Monaco,0.0,0–0,eng,Tottenham,0.0,11365.0,Stade Louis II,Marco Guida,NaN,main stage,False,False,NaN,NaN,NaN
3272,1024,Champions League,2025/26,2025,League phase,3.0,Wed,2025-10-22,21:00,es,Real Madrid,1.0,1–0,it,Juventus,0.0,76521.0,Estadio Santiago Bernabéu,Slavko Vinčič,NaN,main stage,False,False,NaN,NaN,NaN
3273,1026,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,18:45,it,Napoli,0.0,0–0,de,Frankfurt,0.0,45840.0,Stadio Diego Armando Maradona,João Pinheiro,NaN,main stage,False,False,NaN,NaN,NaN
3274,1027,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,18:45,cz,Slavia Prague,0.0,0–3,eng,Arsenal,3.0,19222.0,Fortuna Arena,Əliyar Ağayev,NaN,main stage,False,False,NaN,NaN,NaN
3275,1028,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,20:00,eng,Tottenham,4.0,4–0,dk,FC Copenhagen,0.0,49565.0,Tottenham Hotspur Stadium,Erik Lambrechts,NaN,main stage,False,False,NaN,NaN,NaN
3276,1029,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,20:00,eng,Liverpool,1.0,1–0,es,Real Madrid,0.0,59916.0,Anfield,István Kovács,NaN,main stage,False,False,NaN,NaN,NaN
3277,1030,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,21:00,fr,PSG,1.0,1–2,de,Bayern Munich,2.0,45747.0,Parc des Princes,Maurizio Mariani,NaN,main stage,False,False,NaN,NaN,NaN
3278,1031,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,21:00,it,Juventus,1.0,1–1,pt,Sporting CP,1.0,40729.0,Allianz Stadium,Daniel Siebert,NaN,main stage,False,False,NaN,NaN,NaN
3279,1032,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,21:00,es,Atlético Madrid,3.0,3–1,be,Union SG,1.0,59347.0,Riyadh Air Metropolitano,Espen Eskås,NaN,main stage,False,False,NaN,NaN,NaN
3280,1033,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,21:00,no,Bodø/Glimt,0.0,0–1,fr,Monaco,1.0,7842.0,Aspmyra Stadion,Damian Sylwestrzak,NaN,main stage,False,False,NaN,NaN,NaN
3281,1034,Champions League,2025/26,2025,League phase,4.0,Tue,2025-11-04,22:00,gr,Olympiacos,1.0,1–1,nl,PSV,1.0,32570.0,Stadio Georgios Karaiskáki,Clément Turpin,NaN,main stage,False,False,NaN,NaN,NaN
3282,1035,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,19:45,cy,Pafos FC,1.0,1–0,es,Villarreal,0.0,6314.0,Alphamega Stadium,Sven Jablonski,NaN,main stage,False,False,NaN,NaN,NaN
3283,1036,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,20:00,eng,Manchester City,4.0,4–1,de,Dortmund,1.0,50513.0,Etihad Stadium,Szymon Marciniak,NaN,main stage,False,False,NaN,NaN,NaN
3284,1037,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,20:00,eng,Newcastle,2.0,2–0,es,Athletic Club,0.0,51923.0,St James' Park,Ivan Kružliak,NaN,main stage,False,False,NaN,NaN,NaN
3285,1038,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,20:00,pt,Benfica,0.0,0–1,de,Leverkusen,1.0,55796.0,Estádio do Sport Lisboa e Benfica,Simone Sozza,NaN,main stage,False,False,NaN,NaN,NaN
3286,1039,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,21:00,fr,Marseille,0.0,0–1,it,Atalanta,1.0,64319.0,Orange Vélodrome,Jose Maria Sánchez,NaN,main stage,False,False,NaN,NaN,NaN
3287,1040,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,21:00,nl,Ajax,0.0,0–3,tr,Galatasaray,3.0,51000.0,Johan Cruijff Arena,Benoît Bastien,NaN,main stage,False,False,NaN,NaN,NaN
3288,1041,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,21:00,it,Inter,2.0,2–1,kz,FC Kairat,1.0,69983.0,Stadio Giuseppe Meazza,Luís Godinho,NaN,main stage,False,False,NaN,NaN,NaN
3289,1042,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,21:00,be,Club Brugge,3.0,3–3,es,Barcelona,3.0,27037.0,Jan Breydelstadion,Anthony Taylor,NaN,main stage,False,False,NaN,NaN,NaN
3290,1043,Champions League,2025/26,2025,League phase,4.0,Wed,2025-11-05,21:45,az,Qarabağ,2.0,2–2,eng,Chelsea,2.0,30887.0,Tofiq Bəhramov adına Respublika stadionu,Sebastian Gishamer,NaN,main stage,False,False,NaN,NaN,NaN
3291,1045,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,18:45,nl,Ajax,0.0,0–2,pt,Benfica,2.0,51154.0,Johan Cruijff Arena,Sven Jablonski,NaN,main stage,False,False,NaN,NaN,NaN
3292,1046,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,20:00,eng,Chelsea,3.0,3–0,es,Barcelona,0.0,39323.0,Stamford Bridge,Slavko Vinčič,NaN,main stage,False,False,NaN,NaN,NaN
3293,1047,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,20:00,eng,Manchester City,0.0,0–2,de,Leverkusen,2.0,50592.0,Etihad Stadium,João Pinheiro,NaN,main stage,False,False,NaN,NaN,NaN
3294,1048,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,20:45,tr,Galatasaray,0.0,0–1,be,Union SG,1.0,45444.0,RAMS Park,Jose Maria Sánchez,NaN,main stage,False,False,NaN,NaN,NaN
3295,1049,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,21:00,no,Bodø/Glimt,2.0,2–3,it,Juventus,3.0,7824.0,Aspmyra Stadion,Danny Makkelie,NaN,main stage,False,False,NaN,NaN,NaN
3296,1050,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,21:00,it,Napoli,2.0,2–0,az,Qarabağ,0.0,32019.0,Stadio Diego Armando Maradona,Szymon Marciniak,NaN,main stage,False,False,NaN,NaN,NaN
3297,1051,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,21:00,de,Dortmund,4.0,4–0,es,Villarreal,0.0,81365.0,Signal Iduna Park,Davide Massa,NaN,main stage,False,False,NaN,NaN,NaN
3298,1052,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,21:00,cz,Slavia Prague,0.0,0–0,es,Athletic Club,0.0,19169.0,Fortuna Arena,Donatas Rumšas,NaN,main stage,False,False,NaN,NaN,NaN
3299,1053,Champions League,2025/26,2025,League phase,5.0,Tue,2025-11-25,21:00,fr,Marseille,2.0,2–1,eng,Newcastle,1.0,64521.0,Orange Vélodrome,Maurizio Mariani,NaN,main stage,False,False,NaN,NaN,NaN
3300,1054,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,18:45,dk,FC Copenhagen,3.0,3–2,kz,FC Kairat,2.0,30231.0,Parken,Nick Walsh,NaN,main stage,False,False,NaN,NaN,NaN
3301,1055,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,19:45,cy,Pafos FC,2.0,2–2,fr,Monaco,2.0,8347.0,Alphamega Stadium,Ivan Kružliak,NaN,main stage,False,False,NaN,NaN,NaN
3302,1056,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,20:00,pt,Sporting CP,3.0,3–0,be,Club Brugge,0.0,41634.0,Estádio José Alvalade,Tobias Stieler,NaN,main stage,False,False,NaN,NaN,NaN
3303,1057,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,20:00,eng,Arsenal,3.0,3–1,de,Bayern Munich,1.0,58780.0,Emirates Stadium,Marco Guida,NaN,main stage,False,False,NaN,NaN,NaN
3304,1058,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,20:00,eng,Liverpool,1.0,1–4,nl,PSV,4.0,59964.0,Anfield,Alejandro Hernández,NaN,main stage,False,False,NaN,NaN,NaN
3305,1059,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,21:00,es,Atlético Madrid,2.0,2–1,it,Inter,1.0,68069.0,Riyadh Air Metropolitano,François Letexier,NaN,main stage,False,False,NaN,NaN,NaN
3306,1060,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,21:00,de,Frankfurt,0.0,0–3,it,Atalanta,3.0,59500.0,Deutsche Bank Park,Chris Kavanagh,NaN,main stage,False,False,NaN,NaN,NaN
3307,1061,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,21:00,fr,PSG,5.0,5–3,eng,Tottenham,3.0,47574.0,Parc des Princes,Felix Zwayer,NaN,main stage,False,False,NaN,NaN,NaN
3308,1062,Champions League,2025/26,2025,League phase,5.0,Wed,2025-11-26,22:00,gr,Olympiacos,3.0,3–4,es,Real Madrid,4.0,32325.0,Stadio Georgios Karaiskáki,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN
3309,1064,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,18:45,de,Bayern Munich,3.0,3–1,pt,Sporting CP,1.0,75000.0,Allianz Arena,Nick Walsh,NaN,main stage,False,False,NaN,NaN,NaN
3310,1065,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,20:00,eng,Tottenham,3.0,3–0,cz,Slavia Prague,0.0,47281.0,Tottenham Hotspur Stadium,Benoît Bastien,NaN,main stage,False,False,NaN,NaN,NaN
3311,1066,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,20:30,kz,FC Kairat,0.0,0–1,gr,Olympiacos,1.0,19463.0,Astana Arena,Juan Martínez,NaN,main stage,False,False,NaN,NaN,NaN
3312,1067,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,nl,PSV,2.0,2–3,es,Atlético Madrid,3.0,34800.0,Philips Stadion,Michael Oliver,NaN,main stage,False,False,NaN,NaN,NaN
3313,1068,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,it,Inter,0.0,0–1,eng,Liverpool,1.0,73892.0,Stadio Giuseppe Meazza,Felix Zwayer,NaN,main stage,False,False,NaN,NaN,NaN
3314,1069,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,fr,Monaco,1.0,1–0,tr,Galatasaray,0.0,9887.0,Stade Louis II,Danny Makkelie,NaN,main stage,False,False,NaN,NaN,NaN
3315,1070,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,be,Union SG,2.0,2–3,fr,Marseille,3.0,16214.0,Lotto Park,João Pinheiro,NaN,main stage,False,False,NaN,NaN,NaN
3316,1071,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,it,Atalanta,2.0,2–1,eng,Chelsea,1.0,20685.0,New Balance Arena,Alejandro Hernández,NaN,main stage,False,False,NaN,NaN,NaN
3317,1072,Champions League,2025/26,2025,League phase,6.0,Tue,2025-12-09,21:00,es,Barcelona,2.0,2–1,de,Frankfurt,1.0,38439.0,Spotify Camp Nou,Davide Massa,NaN,main stage,False,False,NaN,NaN,NaN
3318,1073,Champions League,2025/26,2025,League phase,6.0,Wed,2025-12-10,18:45,es,Villarreal,2.0,2–3,dk,FC Copenhagen,3.0,17023.0,Estadio de la Cerámica,Ivan Kružliak,NaN,main stage,False,False,NaN,NaN,NaN

In [ ]:
pd.reset_option('display.max_rows')